# The main entry point of the workflow.
# After configuring, running snakemake -n in a clone of this repository should successfully execute a dry-run of the workflow.



rule all:
	input:
		'results/GWAS/checks/GWAS_performed.txt',
#		'results/GWAS/checks_non_rel/GWAS_performed.txt',
		'results/GWAS/checks_non_rel_lm/GWAS_performed.txt',
		'results/LDAK/checks/h2_performed.txt',
		'results/effect_origin/poisson/miscarriage/fets_poisson.txt',
		'results/HWE/miscarriage/fets_HWE.txt',
		'reports/miscarriage_fets.html',
		'results/plots/polygenicity-contrast-jaundice.png'
#		'results/HESS/checks/h2_estimated.txt',
#		'results/plots/checks/manhattan-jaundice.txt',
#		'results/plots/checks/HESS-plot.txt',
#		'results/topregions/delivery/checks/QC_performed.txt'

include: "rules/common.smk"
include: "rules/phenotype.smk"
include: "rules/GWAS.smk"
include: "rules/QC_GWAS.smk"
include: "rules/COJO.smk"
include: "rules/effect_origin.smk"
include: "rules/figures.smk"
include: "rules/HESS.smk"
include: "rules/PGS.smk"
include: "rules/total_bilirubin.smk"
include: "rules/ABO.smk"
include: "rules/colocalization.smk"
include: "rules/merge_all_data.smk"
include: "rules/conditional_GWAS.smk"
include: "rules/UGT1A4-missense.smk"
include: "rules/eQTL_catalogue.smk"
include: "rules/estimate_LD.smk"
include: "rules/LDAK.smk"
include: "rules/HWE.smk"
include: "rules/reports.smk"
